### ISSUE TITLE
[FEATURE] Remove custom stack class in favour of std:array

### ISSUE THREAD

**Issue by cstatz** [cstatz/blazert#38]
**Is your feature request related to a problem? Please describe.**
You should not reinvent the wheel. Use stl datatypes if they solve your problem.

**Describe a possible solution.**
Replace custom stack class with std::array.

**Comment by orgarten** [comment]
I did implement std::array based stack in #44. std::array alone is not enough to provide the needed functionality at this point.

**Comment by orgarten** [comment]
Since #44 is closed because it did not provide any improvement over the current solution, especially with regard to readability, this can be closed, too.
