### ISSUE TITLE
[FEATURE] Enhance/Create API Documentation for the HL-API

### ISSUE THREAD

**Issue by cstatz** [cstatz/blazert#42]
**Is your feature request related to a problem? Please describe.**
Currently there is no or little documentation of the API. 

**Describe a possible solution.**
At least a proper documentation of the High-Level-(Scene-)API should be created. 
From the source-code documentation a tex, html or md document should be created.

**Describe alternatives you've considered**
Just let the developer figure this out.
Generate a API for all functions, classes, types.

**Comment by orgarten** [comment]
After some research, doxygen seems to be the only viable option to generate a good C++ documentation. 

I will go ahead and setup the appropriate files in an extra branch and write more documentation regarding the high level API.

**Comment by orgarten** [comment]
Files to comment (important for users):
- [ ] blazert/scene.h
- [ ] blazert/embree/scene.h
- [ ] blazert/ray.h
- [ ] blazert/datatypes.h

**Comment by orgarten** [comment]
The current setup is as follows:
* doxygen for API reference generation
* breathe to include doxygen documentaion in sphinx
* sphinx for documentation of everything
